export const CRYSTALS_LOADING_TOGGLE = 'CRYSTALS_LOADING_TOGGLE';
export const CRYSTALS_INTEREST_SET = 'CRYSTALS_INTEREST_SET';
export const CRYSTALS_PRICE_SET = 'CRYSTALS_PRICE_SET';
export const CRYSTALS_ITEMS_SET = 'CRYSTALS_ITEMS_SET';
export const CRYSTALS_TEXT_SET = 'CRYSTALS_TEXT_SET';

export const FIREBASE_VALUES_SET = 'FIREBASE_VALUES_SET';
export const FIREBASE_LOADED_SET = 'FIREBASE_LOADED_SET';

export const CLI_COMMAND_SET = 'CLI_COMMAND_SET';
export const CLI_LOADING_SET = 'CLI_LOADING_SET';
export const CLI_RESULT_SET = 'CLI_RESULT_SET';

export const MARKET_FILTER_SET = 'MARKET_FILTER_SET';
